
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 12 09:27:52 GMT 2017
//----------------------------------------------------

package analyse;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Dec 12 09:27:52 GMT 2017
  */
public class AnalyserSyntaxique extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalyserSyntaxique() {super();}

  /** Constructor which sets the default scanner. */
  public AnalyserSyntaxique(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalyserSyntaxique(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\021\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\004\000\002\004\004" +
    "\000\002\005\004\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\011\005\000\002" +
    "\011\005\000\002\011\003\000\002\007\006\000\002\010" +
    "\003\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\012\012\013\013\007\014\004\015\011\001" +
    "\002\000\014\004\ufff1\005\ufff1\007\ufff1\011\ufff1\016\ufff1" +
    "\001\002\000\004\002\042\001\002\000\014\002\ufffe\012" +
    "\ufffe\013\ufffe\014\ufffe\015\ufffe\001\002\000\004\014\041" +
    "\001\002\000\004\005\036\001\002\000\014\004\ufff2\005" +
    "\ufff2\007\ufff2\011\ufff2\016\ufff2\001\002\000\004\004\035" +
    "\001\002\000\004\006\032\001\002\000\004\004\031\001" +
    "\002\000\014\002\000\012\013\013\007\014\004\015\011" +
    "\001\002\000\004\005\017\001\002\000\012\010\022\012" +
    "\013\014\004\015\011\001\002\000\004\004\ufffa\001\002" +
    "\000\006\004\ufff9\016\025\001\002\000\010\010\022\014" +
    "\004\015\011\001\002\000\010\004\ufff4\011\ufff4\016\ufff4" +
    "\001\002\000\006\011\026\016\025\001\002\000\010\010" +
    "\022\014\004\015\011\001\002\000\010\004\ufff5\011\ufff5" +
    "\016\ufff5\001\002\000\010\004\ufff6\011\ufff6\016\ufff6\001" +
    "\002\000\014\002\uffff\012\uffff\013\uffff\014\uffff\015\uffff" +
    "\001\002\000\014\002\ufffc\012\ufffc\013\ufffc\014\ufffc\015" +
    "\ufffc\001\002\000\006\014\004\015\011\001\002\000\004" +
    "\007\034\001\002\000\006\004\ufff3\005\ufff3\001\002\000" +
    "\014\002\ufffd\012\ufffd\013\ufffd\014\ufffd\015\ufffd\001\002" +
    "\000\012\010\022\012\013\014\004\015\011\001\002\000" +
    "\004\004\ufff7\001\002\000\006\004\ufff8\016\025\001\002" +
    "\000\004\004\ufffb\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\020\002\004\003\014\004\005\005\011\006" +
    "\013\007\015\010\007\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\004\027\005\011\006\013\007" +
    "\015\010\007\001\001\000\002\001\001\000\010\007\017" +
    "\010\022\011\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\022\011\023\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\010\022\011\026\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\007\036\010\022" +
    "\011\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalyserSyntaxique$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalyserSyntaxique$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalyserSyntaxique$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /* Change the method report_error so it will display the line and column of where the error
       occurred in the input as well as the reason for the error which is passed into the method
       in the String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuffer called 'm' with the string 'Error' in it. */
        StringBuffer m = new StringBuffer("Error");
   
        /* Check if the information passed to the method is the same type as the type 
           java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the information in the object 
               info that is being typecasted as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuffer error message the line number of the error 
                   in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuffer error message the column number of the 
                       error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
        /* Add to the end of the StringBuffer error message created in this method the message that
           was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuffer 'm', which contains an error message, out on 
           a line. */
        System.err.println(m);
    }
    /* Change the method report_fatal_error so when it reports a fatal error it will display the 
       line and column number of where the fatal error occurred in the input as well as the reason
       for the fatal error which is passed into the method in the object 'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalyserSyntaxique$actions {

 /* vide pour le moment */
	    
  private final AnalyserSyntaxique parser;

  /** Constructor */
  CUP$AnalyserSyntaxique$actions(AnalyserSyntaxique parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalyserSyntaxique$do_action(
    int                        CUP$AnalyserSyntaxique$act_num,
    java_cup.runtime.lr_parser CUP$AnalyserSyntaxique$parser,
    java.util.Stack            CUP$AnalyserSyntaxique$stack,
    int                        CUP$AnalyserSyntaxique$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalyserSyntaxique$result;

      /* select the action based on the action number */
      switch (CUP$AnalyserSyntaxique$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // INDICE ::= CSTE 
            {
              String RESULT =null;
		int zleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int zright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String z = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 RESULT = z; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("INDICE",6, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // INDICE ::= VAR 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 RESULT = i; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("INDICE",6, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // TAB ::= TABNAME CROCHETOUVERT INDICE CROCHETFERMER 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).value;
		 RESULT = i; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("TAB",5, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-3)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // EXP ::= INDICE 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 RESULT = i; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("EXP",7, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // EXP ::= PAROUVERT EXP PARFERMER 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).value;
		 RESULT ="("+e+")"; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("EXP",7, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // EXP ::= EXP OP EXP 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 RESULT = e1+" "+o+" "+e2; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("EXP",7, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // AFF ::= INDICE EGAL TAB 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 System.out.println("affecation case "+b+" dans "+a) ; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("AFF",4, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // AFF ::= INDICE EGAL EXP 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 System.out.println("affectation de l'expression("+b+") dans "+a) ; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("AFF",4, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // AFF ::= TAB EGAL EXP 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 System.out.println("affectation de l'expression("+b+") dans case "+a) ; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("AFF",4, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // AFF ::= TAB EGAL TAB 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 System.out.println("affectation case "+b+" dans case "+a) ; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("AFF",4, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-2)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // DECL ::= TYPEPRIMITIF CSTE 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.peek()).value;
		 System.out.println(i + " de type primitif " + t) ; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("DECL",3, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INST ::= AFF POINTVIRGULE 
            {
              String RESULT =null;

              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("INST",2, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INST ::= DECL POINTVIRGULE 
            {
              String RESULT =null;

              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("INST",2, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LINST ::= INST 
            {
              String RESULT =null;

              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("LINST",1, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LINST ::= LINST INST 
            {
              String RESULT =null;

              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("LINST",1, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // PROG ::= LINST 
            {
              String RESULT =null;
		 System.out.println("fini !") ; 
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("PROG",0, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          return CUP$AnalyserSyntaxique$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= PROG EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)).value;
		RESULT = start_val;
              CUP$AnalyserSyntaxique$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.elementAt(CUP$AnalyserSyntaxique$top-1)), ((java_cup.runtime.Symbol)CUP$AnalyserSyntaxique$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalyserSyntaxique$parser.done_parsing();
          return CUP$AnalyserSyntaxique$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

