
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 12 10:41:49 GMT 2017
//----------------------------------------------------

package analyse;

/** CUP generated class containing symbol constants. */
public class CodeLexicaux {
  /* terminals */
  public static final int OP = 12;
  public static final int POINTVIRGULE = 2;
  public static final int CSTE = 10;
  public static final int TYPEPRIMITIF = 9;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int EGAL = 3;
  public static final int CROCHETOUVERT = 4;
  public static final int CROCHETFERMER = 5;
  public static final int PAROUVERT = 6;
  public static final int TABNAME = 8;
  public static final int PARFERMER = 7;
  public static final int error = 1;
}

